In [1]:
%cd "~/moses-incons-pen-xp"
%load_ext autoreload
%autoreload 2


/home/xabush/moses-incons-pen-xp


In [3]:
import sys
sys.path.append("/usr/local/lib/python3.8/dist-packages")

In [2]:
import pandas as pd
import numpy as np
from notebooks.variable_selection.custom_model import *
from sklearn.model_selection import GridSearchCV

In [185]:
beta1_y = pd.read_csv("data/Li2008/y_betas/y_beta1.csv")
train1_df = pd.read_csv("data/Li2008/beta1/train1.csv")
X, y = train1_df[train1_df.columns.difference(["y"])], beta1_y["train1"]
train1_df.head()

y     TF1   TF1g1   TF1g2   TF1g3   TF1g4   TF1g5   TF1g6   TF1g7   TF1g8  \
0  0 -1.5165 -0.8115 -0.3562 -1.5629 -2.1856 -0.8701 -1.5197 -0.3622 -1.4106   
1  1  1.4627  0.4422  1.9967  1.2537  0.5932  2.1607  0.7268  1.2101  1.2913   
2  1  0.9093  0.6089  0.4935  0.2650  1.2553  0.1035  0.8043  0.4336  1.1341   
3  0 -0.5444  0.0011 -0.4314 -0.5304 -1.1213  0.1714 -0.7389 -0.7719 -0.3342   
4  1  0.5121  1.1357  0.6240 -0.1818  0.3880  0.8500  0.0440  0.0895  0.1684   

   ...  TF200g1  TF200g2  TF200g3  TF200g4  TF200g5  TF200g6  TF200g7  \
0  ...  -1.4188  -0.8440  -1.2232  -1.2117  -0.5672  -0.1177  -0.3543   
1  ...   0.6158   0.3613  -0.0918   0.2916   0.2039   0.9683   0.3107   
2  ...   1.1829   0.3388   0.9161   0.9376   0.7844   0.5766   1.1675   
3  ...  -0.6344  -0.5307  -1.3859  -1.7020  -0.6773  -0.7879  -0.8221   
4  ...  -0.9807   0.5128   1.1377  -0.3012  -0.4148   0.9216  -0.1016   

   TF200g8  TF200g9  TF200g10  
0  -0.4383  -0.9867    0.1272  
1   0.6279  -0.2370   -0.2595  
2   1.1204   1.2453    1.2618  
3  -0.3707  -0.4189   -0.4838  
4  -0.4590   0.3377    0.2245  

[5 rows x 2201 columns]

In [187]:
train1_contin = pd.concat([y, X], axis=1)
train1_contin.rename(columns={"train1": "y"}, inplace=True)
train1_contin.to_csv("data/Li2008/beta1/train1_contin.csv", index=False)
train1_contin

y     TF1    TF10   TF100  TF100g1  TF100g10  TF100g2  TF100g3  \
0  -69.465965 -1.5165 -1.8580 -0.6363  -0.5566   -0.5426  -0.4570  -0.4322   
1   37.608878  1.4627  2.0399 -1.3733  -1.5491    0.2329  -0.2554  -1.6635   
2   26.729028  0.9093  1.5163 -0.1892  -0.3427   -1.1153  -0.4356   0.0840   
3  -41.303925 -0.5444  0.0940 -0.6367  -0.6540    0.1439  -0.7711  -0.9095   
4    3.904698  0.5121 -0.6611 -0.2873  -0.0808   -0.3123  -0.6502  -0.3691   
..        ...     ...     ...     ...      ...       ...      ...      ...   
95  65.441353  0.9398  0.4634  1.5387   0.6812    1.8702   0.2214   1.5680   
96   0.687377 -2.9457  1.0205 -0.7332  -0.8407    0.1591  -1.2701  -0.2958   
97   0.198313  0.3351 -0.2952 -0.2817  -0.2847    0.7004   0.3293   0.2123   
98  33.619386  0.6948 -1.3352 -1.0782  -0.5874   -1.0762  -0.4258  -0.1818   
99  37.826166  1.2116 -0.4184  0.3858  -0.5008    1.4578   1.2192  -0.0064   

    TF100g4  TF100g5  ...   TF9g1  TF9g10   TF9g2   TF9g3   TF9g4   TF9g5  \
0    0.5636   0.5911  ...  0.6709  0.3656 -0.0256  0.4763  0.1145  0.1980   
1   -1.5650  -1.4238  ...  1.4258  1.8623  1.1627  1.6505  1.9165  0.5123   
2    0.0885  -0.7811  ...  1.0221  0.3324 -0.2786 -0.2369 -0.1276 -0.0342   
3   -0.4795   0.0582  ...  0.5962  1.1450  0.3241  0.4297  0.4719  0.7388   
4    0.5075  -0.2808  ... -0.1319 -0.5565 -0.8845 -0.3720 -1.2144 -0.9505   
..      ...      ...  ...     ...     ...     ...     ...     ...     ...   
95   1.1311   1.1201  ...  0.1576 -0.2709  0.7397  0.1189 -0.3730  0.2267   
96  -0.5602  -1.8333  ...  0.1490 -0.7517  0.9736  0.4583  0.1253  0.3335   
97  -0.8887  -0.4374  ... -0.9049 -0.5071 -1.2352  0.3870 -0.0083  0.6649   
98  -0.7085  -0.9082  ... -1.0867 -1.2145 -0.7220 -0.5988 -0.6164 -1.4100   
99  -0.2970  -0.3221  ... -1.3626 -1.9806 -2.0524 -1.1045 -1.6343 -2.0277   

     TF9g6   TF9g7   TF9g8   TF9g9  
0   0.5041 -0.1537  0.5332  0.6933  
1   1.4859  1.7212  1.1304  2.0692  
2  -0.8183  0.2453  0.3041 -0.7992  
3   0.0140  0.7429  1.3787  0.7931  
4  -0.0787 -0.3578  0.9971 -0.0577  
..     ...     ...     ...     ...  
95  0.1119 -0.4108  0.0996  0.2201  
96  0.8109 -0.3028  0.3651  1.4440  
97  0.1658 -0.7963 -0.4795 -0.2553  
98 -1.3713  0.0974 -0.9165 -2.3823  
99 -0.3368 -0.8770 -1.7382 -0.7291  

[100 rows x 2201 columns]

In [ ]:
test1_df = pd.read_csv("data/Li2008/beta1/test1.csv")
X_test, y_test = test1_df[test1_df.columns.difference(["y"])], beta1_y["test1"]
test1_df.head()

In [188]:
test1_contin = pd.concat([y_test, X_test], axis=1)
test1_contin.rename(columns={"test1": "y"}, inplace=True)
test1_contin.to_csv("data/Li2008/beta1/test1_contin.csv", index=False)

In [24]:
import networkx as nx

G = nx.Graph()
for i in range(1, 201):
    G.add_node(f"TF{i}")
    for g in range(1, 11):
        G.add_node(f"TF{i}g{g}")
        G.add_edge(f"TF{i}", f"TF{i}g{g}", weight=0.7)

len(G)

2200

In [27]:
num_nodes = len(G.nodes)
L = np.zeros(shape=(num_nodes, num_nodes))

i, j = 0, 0
for u in G.nodes:
    neighbors = [n for n in G.neighbors(u)]
    d_u = len(neighbors) * 0.7
    for v in G.nodes:
        if u == v:
            L[i, j] = 1
        elif v in neighbors:
            d_v = len([n for n in G.neighbors(v)]) * 0.7

            L[i, j] = -0.7 / math.sqrt(d_u * d_v)

        j += 1

    j = 0
    i += 1


In [308]:
S = nx.linalg.graphmatrix.incidence_matrix(G, oriented=True, weight="weight").toarray()

In [314]:
S.shape

(2200, 2000)

In [277]:

from sklearn.preprocessing import StandardScaler

xscaler = StandardScaler().fit(X)
X_scaled = xscaler.fit_transform(X)
yscaler = StandardScaler().fit(np.array(y).reshape(-1, 1))
y_scaled = yscaler.fit_transform(np.array(y).reshape(-1, 1))
y_scaled = np.ndarray.flatten(y_scaled)

In [345]:
from sklearn.linear_model import LassoCV
from notebooks.variable_selection.custom_model import *
lasso_cv = LassoCV(cv=5, fit_intercept=False)
network_reg = NetworkRegLasso(reg1=0.1, reg2=1000)
X_star, y_star = network_reg.augment_data(X_scaled, y_scaled, S)
lasso_cv.fit(X_star, y_star)
lasso_cv.score(X_star, y_star)

/home/xabush/moses-incons-pen-xp/venv/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.enet_coordinate_descent(
/home/xabush/moses-incons-pen-xp/venv/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.014932359764664282, tolerance: 0.010000000000000002
  model = cd_fast.enet_coordinate_descent(
/home/xabush/moses-incons-pen-xp/venv/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.020014216833918602, tolerance: 0.010000000000000002
  model = cd_fast.enet_coordinate_descent(
/home/xabush/moses-incons-pen-xp/venv/lib/python3.8/site

0.0

In [344]:
y_star.shape

(2300,)

In [298]:
lasso_cv.score(X_scaled, y_scaled)

0.0

In [338]:
from notebooks.variable_selection.custom_model import *
network_reg = NetworkRegLasso(reg1=0.012, reg2=10000)
network_reg.fit(X_scaled, y_scaled, S)

NetworkRegLasso(reg1=0.012, reg2=10000)

In [340]:
np.where(network_reg.coef_ != 0)

(array([   0,    3,    6,   89,  497,  498,  500,  507,  638,  699,  759,
        1028, 1031, 1083, 1087, 1210, 1211, 1212, 1213, 1214, 1215, 1216,
        1217, 1218, 1219, 1220, 1349, 1350, 1352, 1353, 1466, 1468, 1471,
        1634, 1641]),)

In [341]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = network_reg.predict(X_scaled)
y_inv = yscaler.inverse_transform(y_pred)
r2_score(y, y_inv)

0.033739622038597594

In [323]:
y_inv

array([-3.22750547, 15.55177043, 15.04984547,  0.03079299,  6.97115787,
       10.89346307,  3.12478966,  3.87017633,  1.78964356,  2.79957672,
        9.32162312,  5.4240827 ,  7.88951197,  9.84360542, 13.59284054,
        6.39958039, 11.74416186, -1.22142303,  5.26592327,  6.30211199,
        7.3666207 ,  8.88651505,  5.80996716, 11.36377311,  5.69442845,
       10.4523063 ,  0.90770385, 11.04921899, 18.00975541, 16.03763021,
        6.83800559,  5.70783612, 11.49309826,  5.36681109, -0.964254  ,
        4.73945214, 12.87647482,  7.72864236,  7.93645443,  8.34491128,
       10.5343272 ,  4.4768239 ,  6.85574347,  9.01732737,  0.79516276,
        3.66406511,  8.42242286,  2.22963638,  2.97288053, 14.60075584,
       -1.95050564, 14.43715295,  8.64686062,  1.24414788,  0.36885661,
       -2.4847346 ,  7.13706291,  7.21394534, 12.48935729, 12.79093451,
        1.08418586,  9.14349002,  6.34676486, 10.18955778, 14.41775623,
        1.95194712,  5.03069772,  4.25497071,  8.20632858,  4.09

In [281]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [256]:
network_reg.score(X, y)

-205.88169986753417

In [257]:
np.where(network_reg.coef_ != 0)

(array([   3,    6,   15,   27,   89,   95,  115,  208,  216,  225,  242,
         305,  318,  338,  341,  374,  473,  475,  480,  487,  505,  539,
         551,  571,  616,  617,  627,  638,  702,  759,  787,  809,  864,
         875,  881,  918,  922,  939,  949,  952,  953,  994, 1005, 1028,
        1031, 1067, 1083, 1094, 1150, 1196, 1204, 1212, 1214, 1217, 1220,
        1308, 1339, 1343, 1349, 1350, 1352, 1455, 1462, 1468, 1471, 1564,
        1634, 1641, 1711, 1715, 1723, 1757, 1797, 1827, 1865, 1896, 1899,
        1909, 1970, 1974, 2022, 2039, 2092, 2106, 2109, 2163, 2191, 2196]),)

In [240]:
network_reg.score(X_test, y_test)

-1826.252361200974

In [151]:
from sklearn.linear_model import Lasso
X_star, y_star = network_reg.augment_data(X, y, L)
lasso = Lasso(alpha=0.6)
lasso.fit(X_star, y_star)
y_pred = lasso.predict(X_test)

2043.6624683782418

In [ ]:
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(cv=10, random_state=42, n_jobs=-1, max_iter=10000, n_alphas=1000, normalize=True )
lasso_cv.fit(X_star, y_star)

/home/xabush/moses-incons-pen-xp/venv/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.enet_coordinate_descent(


In [140]:
np.where(lasso_cv.coef_ != 0)

(array([   3,   10,   27,   89,   95,  115,  242,  487,  498,  616,  759,
         787,  864,  875,  922,  949,  952, 1028, 1083, 1094, 1212, 1213,
        1214, 1339, 1343, 1350, 1352, 1468, 1471, 1615, 1617, 1634, 1641,
        1757, 1797, 1865, 1980, 2039, 2109]),)

In [126]:
lasso_cv.fit(X, y)

LassoCV(cv=10, random_state=42)

In [146]:
lasso_cv.score(X_test, y_test)

0.24585833633935705

In [144]:
lasso_cv.alpha_

0.022307668672097672

In [183]:
network_reg = NetworkRegLasso(reg1=0.3842, reg2=1)
network_reg.fit(X, train1_df["y"], L)

NetworkRegLasso(reg1=0.3842, reg2=1)